spring:
  rsocket:
    server:
      port: 6565
      transport: websocket
  r2dbc:
    properties:
      schema: green_chat
      sslmode: require
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres

flyway:
  url: jdbc:postgresql://localhost:5432/green_chat
  username: postgres
  password:
  database: postgres