datasource:
  url: postgresql://localhost
  port: 5432
  username: postgres
  password: postgres
  ssl: false
  sslMode: disable

spring:
  rsocket:
    server:
      port: 6565
      transport: websocket
  r2dbc:
    url: r2dbc:${datasource.url}:${datasource.port}/green_chat
    username: ${datasource.username}
    password: ${datasource.password}
    properties:
      schema: green_chat
      ssl: ${datasource.ssl}
      sslMode: ${datasource.sslMode}

flyway:
  url: jdbc:${datasource.url}:${datasource.port}/green_chat
  username: ${datasource.username}
  password: ${datasource.password}
  database: green_chat
  ssl: ${datasource.ssl}
  sslMode: ${datasource.sslMode}