spring:
  rsocket:
    server:
      port: 6565
      transport: websocket
#      ssl:
#        enabled: true
#        key-store: rsocket-server.p12
#        key-store-type: PKCS12
#        key-store-password: password
#        key-alias: rsocket

#logging.level.org.springframework.boot.autoconfigure=DEBUG
