spring:
  rsocket:
    server:
      port: 6565
      transport: websocket
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
    properties:
      ssl: true
      sslMode: require
      schema: green_chat
    pool:
      initial-size: 1
      max-size: 10
      max-idle-time: 30m

flyway:
  url: jdbc:postgresql://localhost:5432/green_chat
  username: postgres
  password:
  database: postgres